"""create_workflow_tables

Revision ID: 355639c2d979
Revises: 
Create Date: 2026-06-13 21:44:09.600216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '355639c2d979'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_workflow_id'), 'workflows', ['workflow_id'], unique=True)
    op.create_table('workflow_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('workflow_type', sa.String(length=255), nullable=False),
    sa.Column('task_queue', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('runtime_loaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_registrations_content_hash'), 'workflow_registrations', ['content_hash'], unique=True)
    op.create_index(op.f('ix_workflow_registrations_workflow_id'), 'workflow_registrations', ['workflow_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('workflow_type', sa.String(length=255), nullable=False),
    sa.Column('task_queue', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_run_id'), 'workflow_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_temporal_workflow_id'), 'workflow_runs', ['temporal_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('dsl_json', sa.JSON(), nullable=False),
    sa.Column('rf_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(length=255), nullable=False),
    sa.Column('task_queue', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_content_hash'), 'workflow_versions', ['content_hash'], unique=True)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_content_hash'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_temporal_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_run_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_workflow_registrations_workflow_id'), table_name='workflow_registrations')
    op.drop_index(op.f('ix_workflow_registrations_content_hash'), table_name='workflow_registrations')
    op.drop_table('workflow_registrations')
    op.drop_index(op.f('ix_workflows_workflow_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
